### ISSUE TITLE
NullReferenceException thrown for invalid template content.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#39]
The following XAML:

    <ListBox Items="{Binding Items}">
      <ListBox.DataTemplates>
        <DataTemplate DataType="vm:TestItem">
          <TextBlock Text="{Binding Header}" FontSize="24"/>
          <TextBlock Text="{Binding SubHeader}"/>
        </DataTemplate>
      </ListBox.DataTemplates>
    </ListBox>

Throws a `NullReferenceException` as reported in #38. It should give an error indicating that <DataTemplate> can only have a single child.

**Comment by SuperJMN** [comment]
Fixed with https://github.com/SuperJMN/OmniXAML/commit/72b54cc483f626d1244cb3a984ce157f45771a5c

It now throws an exception that provides a better explanation of what happened. 
However, It's advisable to catch this exception in the Template Loader (Perspex.Markup), under the `Load` method and wrap it into a concrete message like "The Template cannot contain more than one root object" or something like that. Please, tell me if you need help with this.
