### ISSUE TITLE
Elements should be added to tree before properties set.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#84]
In standard XAML, elements are added to their parents before properties are set. It was changed to be as it currently is because we had no lifecycle notification, but now that we have that (#58), it can be changed back to the correct order.

**Comment by grokys** [comment]
Actually, this one is becoming a blocker too :(

**Comment by SuperJMN** [comment]
I have been looking for the exact moment in which we changed the order, but I haven't found anything! I've looked back because now that I think about it, if I doubt that OmniXAML has ever connected instances to their parents before setting the properties. Anyways, I will modify the behavior. Not as simple as I initially thought, BTW!

**Comment by grokys** [comment]
Yeah, I was looking for that moment too and didn't find it. I'm sure that it was done after creation at some point though - i remember asking you to change it!

**Comment by SuperJMN** [comment]
I hope this fixes this one ;D 
https://github.com/SuperJMN/OmniXAML/commit/c2b86b9d1ae638c788f44bc63d17911986d766fb
